# Generated by Django 5.2.7 on 2025-10-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='estimated_gdp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='exchange_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
